/**
 * Loader for `test/vectors/signing-v3.json`, the cross-language signing vectors.
 *
 * The TypeScript twin of `vorq-client-sdk-python/tests/vectors.py`. The file is
 * generated by `vorq-evm-contracts/test/Vectors.t.sol`, where every case is
 * signed over the digest Foundry derives from that case's own published payload
 * and is then handed to the deployed contract, which must accept it. It is
 * therefore the authority: nothing here restates an expected value.
 *
 * Each case carries a **standard EIP-712 payload** under `typed_data` —
 * `{types, primaryType, domain, message}` — which is exactly what viem's
 * `hashTypedData` and `recoverTypedDataAddress` take. So a test hands the file's
 * own bytes to the encoder rather than rebuilding them, and an SDK's local type
 * table is checked by direct list equality against `typed_data.types`.
 *
 * The only transformation needed is {@link coerce}, and it exists for one
 * reason: JSON has one number type. `uint128`/`uint256` are carried as decimal
 * strings because a 256-bit value does not survive a double, and
 * `bytes`/`bytes32` as `0x` hex. The declared type in `types` says which is
 * which, so the decoding is driven by the file rather than by a hand-written
 * field list that could drift.
 *
 * There is **no private key in the file**: `signer` is only an address. A test
 * therefore cannot re-sign a case and compare against its published
 * `signature`; it signs the case's own message with a local key and recovers
 * against the case's own `typed_data`, which agrees only if the digests agree.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Address } from "viem";
import { ChainContext } from "../src/terms.js";

/** One EIP-712 member list, as the file spells it. */
export type TypeMembers = { name: string; type: string }[];

export interface VectorCase {
  name: string;
  domain: string;
  typed_data: {
    types: Record<string, TypeMembers>;
    primaryType: string;
    domain: Record<string, unknown>;
    message: Record<string, unknown>;
  };
  digest: `0x${string}`;
  signer: Address;
  signature: `0x${string}`;
  extra?: Record<string, unknown>;
}

export const VECTORS = JSON.parse(
  readFileSync(fileURLToPath(new URL("./vectors/signing-v3.json", import.meta.url)), "utf8"),
) as {
  format: string;
  generated_by: string;
  chain_id: number;
  addresses: Record<string, string>;
  domains: Record<string, { domain: Record<string, unknown>; separator: string | null }>;
  cases: VectorCase[];
};

export const CASES: Record<string, VectorCase> = Object.fromEntries(
  VECTORS.cases.map((c) => [c.name, c]),
);

export const ADDRESSES = VECTORS.addresses;

/**
 * The chain context those vectors belong to, built from the file's own block.
 *
 * The file keys the payment token `payment_token`; this SDK's context calls the
 * same address `usdc`, which is the spelling `GET /evm/chain` serves. Its
 * EIP-712 name and version are the file's too, because they differ per network
 * and a hand-written pair would be the one member nothing here could contradict.
 * `decimals` is the one value the file does not carry — it is not signed over.
 */
export const CTX = new ChainContext({
  chainId: VECTORS.chain_id,
  jobRegistry: ADDRESSES.job_registry as Address,
  providerRegistry: ADDRESSES.provider_registry as Address,
  askRegistry: ADDRESSES.ask_registry as Address,
  usdc: ADDRESSES.payment_token as Address,
  decimals: 6,
  tokenDomain: {
    name: VECTORS.domains.payment_token!.domain.name as string,
    version: VECTORS.domains.payment_token!.domain.version as string,
  },
  feeBps: 100,
});

/**
 * A message with each member decoded per its declared EIP-712 type: `uintN`
 * from a decimal string to `bigint`, `bytesN` left as `0x` hex, structs and
 * arrays recursively.
 */
export function coerce(
  types: Record<string, TypeMembers>,
  primary: string,
  message: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const { name, type } of types[primary]!) {
    const value = message[name];
    if (type.endsWith("[]")) {
      out[name] = (value as Record<string, unknown>[]).map((el) =>
        coerce(types, type.slice(0, -2), el),
      );
    } else if (types[type]) {
      out[name] = coerce(types, type, value as Record<string, unknown>);
    } else if (type.startsWith("uint")) {
      out[name] = BigInt(value as string | number);
    } else {
      out[name] = value; // bytesN / address / string arrive ready to use
    }
  }
  return out;
}

/** A case's decoded message members. */
export const message = (name: string): Record<string, unknown> =>
  coerce(
    CASES[name]!.typed_data.types,
    CASES[name]!.typed_data.primaryType,
    CASES[name]!.typed_data.message,
  );

/**
 * A case's `types` without `EIP712Domain` — the shape an SDK declares. The
 * domain's own type list is boilerplate every encoder knows, so no SDK writes
 * it down.
 */
export function localTypes(name: string): Record<string, TypeMembers> {
  const { EIP712Domain: _drop, ...rest } = CASES[name]!.typed_data.types;
  return rest;
}
